import type { Metadata } from "next";
import { Inter, Space_Grotesk, JetBrains_Mono, Instrument_Serif } from 'next/font/google'
import "./globals.css";
import { cn } from "@/lib/utils";
import { Toaster } from "@/components/ui/toast";

const inter = Inter({ subsets: ['latin'], variable: '--font-inter' })
const spaceGrotesk = Space_Grotesk({ subsets: ['latin'], variable: '--font-space-grotesk' })
const jetbrainsMono = JetBrains_Mono({ subsets: ['latin'], variable: '--font-jetbrains-mono' })
const instrumentSerif = Instrument_Serif({ 
  subsets: ['latin'], 
  weight: '400',
  style: ['normal', 'italic'],
  variable: '--font-instrument-serif' 
})

export const metadata: Metadata = {
  title: {
    template: '%s | KAVACH',
    default: 'Dashboard | KAVACH',
  },
  description: 'Find security vulnerabilities in code generated by ChatGPT, Copilot, and Cursor before you ship. OWASP Top 10 detection, powered by Semgrep + Llama 3.1.',
  keywords: 'AI code security, ChatGPT security, Copilot security scanner, OWASP, code vulnerabilities',
  openGraph: {
    title: 'KAVACH — AI Code Security Analyzer',
    description: 'Find security vulnerabilities in AI-generated code before you ship.',
    type: 'website',
  },
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn("dark", inter.variable, spaceGrotesk.variable, jetbrainsMono.variable, instrumentSerif.variable)}>
      <body className={`${inter.variable} ${spaceGrotesk.variable} ${jetbrainsMono.variable} ${instrumentSerif.variable} bg-[#09090B] text-[#FAFAF9] font-body min-h-screen antialiased`}>
        {children}
        <Toaster />
      </body>
    </html>
  );
}
