interface FAQItem {
  q: string
  a: string
}

export default function FAQSection() {
    const faqs: FAQItem[] = [
        {
            q: "Does KAVACH support code generated by Cursor?",
            a: "Yes, KAVACH works seamlessly with code generated by Cursor, GitHub Copilot, ChatGPT, Claude, and any other LLM. If it's code, we can scan it."
        },
        {
            q: "How is this different from standard Semgrep?",
            a: "While we use Semgrep's powerful static analysis engine under the hood, KAVACH adds an AI evaluation layer specifically tuned to catch logic flaws common in LLM-generated code that static analysis misses."
        },
        {
            q: "Is my code sent to OpenAI?",
            a: "No. Our AI evaluation layer uses local open-source models (Llama 3.1) to analyze logic flaws. Your code never leaves our secure, ephemeral infrastructure and is deleted immediately after scanning."
        },
        {
            q: "What languages do you support?",
            a: "Currently in beta, we support Python, TypeScript/JavaScript, Go, and Java. We are rapidly adding support for Rust, C++, and Ruby."
        },
        {
            q: "When will the paid plans be available?",
            a: "KAVACH is currently 100% free during our beta. Pro plans launching in Q2 2025 with advanced AI, PDF reports, and team features."
        }
    ];

    return (
        <section className="py-24 bg-[#FAFAF9] dark:bg-[#09090B] border-t border-zinc-200 dark:border-zinc-800" id="faq">
            <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
                <h2 className="text-3xl md:text-4xl font-heading font-bold text-center mb-12 text-[#18181B] dark:text-[#FAFAF9]">
                    Frequently asked questions
                </h2>
                <div className="space-y-4">
                    {faqs.map((faq, i) => (
                        <details
                            key={i}
                            className="group bg-white dark:bg-[#18181B] rounded-xl border border-zinc-200 dark:border-zinc-800 p-6 cursor-pointer hover:border-[#7C3AED]/50 transition-colors open:border-l-4 open:border-l-[#7C3AED]"
                        >
                            <summary className="flex justify-between items-center font-heading font-semibold text-[#18181B] dark:text-[#FAFAF9] list-none">
                                <span className="flex items-center">
                                    <span className="font-accent italic text-[#7C3AED] mr-3 text-xl">?</span>
                                    {faq.q}
                                </span>
                                <span className="text-xl text-zinc-400 group-open:rotate-180 transition-transform duration-300">▼</span>
                            </summary>
                            <p className="mt-4 font-body text-zinc-600 dark:text-zinc-400 leading-loose ml-7">
                                {faq.a}
                            </p>
                        </details>
                    ))}
                </div>
            </div>
        </section>
    );
}
