'use client'

import * as Icons from './LandingIcons'
import Reveal from './Reveal'
import Link from 'next/link'
import Image from 'next/image'

export default function HeroSection() {
    return (
        <section className="relative overflow-hidden pt-24 pb-16 md:pt-32 md:pb-24 grid-pattern noise-overlay">
            <div className="absolute top-0 left-1/2 -translate-x-1/2 w-[1000px] h-[500px] opacity-30 dark:opacity-20 pointer-events-none">
                <div className="absolute inset-0 bg-gradient-to-r from-purple-400 to-indigo-400 blur-[100px] rounded-full mix-blend-multiply dark:mix-blend-screen" />
            </div>

            <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 relative z-10 text-center">

                <Reveal delay={100}>
                    <h1 className="text-5xl md:text-7xl font-heading font-bold tracking-tighter text-[#18181B] dark:text-[#FAFAF9] mb-4 leading-[1.1]">
                        AI writes your code. <br className="hidden md:block" />
                        <span className="font-accent italic text-[#7C3AED] font-normal tracking-normal">
                            We scan it for security holes.
                        </span>
                    </h1>
                </Reveal>

                <Reveal delay={200}>
                    <p className="mt-6 text-lg md:text-xl font-body text-zinc-600 dark:text-zinc-400 max-w-3xl mx-auto leading-relaxed">
                        The first security scanner built specifically for code generated by ChatGPT, Copilot, Cursor, and other AI tools. Catch logic flaws and OWASP Top 10 issues before you commit.
                    </p>
                </Reveal>

                <Reveal delay={300}>
                    <div className="mt-10 flex flex-col items-center justify-center space-y-4">
                        <Link href="/dashboard">
                          <button className="bg-gradient-to-b from-[#8B5CF6] to-[#7C3AED] text-white px-10 py-4 rounded-lg font-heading font-semibold text-lg transition-all shadow-[inset_0_1px_0_0_rgba(255,255,255,0.2)] hover:scale-[1.02] hover:shadow-xl hover:shadow-purple-500/25 flex items-center justify-center btn-ripple group">
                              <span className="flex items-center">Get Early Access <Icons.ArrowRight className="ml-2 h-5 w-5 group-hover:translate-x-1 transition-transform" /></span>
                          </button>
                        </Link>
                    </div>
                </Reveal>

                <Reveal delay={400}>
                    <div className="mt-12 flex flex-col sm:flex-row items-center justify-center gap-4 sm:gap-8 text-sm text-zinc-500 dark:text-zinc-400 font-mono">
                        <div><span className="text-[#7C3AED] mr-2">•</span>Powered by Semgrep + Qwen 2.5 Coder</div>
                        <div className="hidden sm:block opacity-30">|</div>
                        <div><span className="text-[#7C3AED] mr-2">•</span>Zero data retention</div>
                        <div className="hidden sm:block opacity-30">|</div>
                        <div><span className="text-[#7C3AED] mr-2">•</span>Open Source</div>
                    </div>
                </Reveal>

                <Reveal delay={600} className="mt-16 mx-auto max-w-5xl relative">
                    {/* Floating Labels */}
                    <div className="absolute -top-4 -right-4 hidden md:flex items-center gap-2 bg-white dark:bg-[#18181B] border border-[#7C3AED]/30 text-zinc-900 dark:text-[#FAFAF9] px-3 py-1.5 rounded-full text-xs font-mono shadow-xl shadow-purple-500/10 z-10 animate-bounce" style={{ animationDuration: '3s' }}>
                        <span className="w-2 h-2 rounded-full bg-[#34D399]"></span>
                        AI-powered scoring
                    </div>
                    <div className="absolute top-32 -left-8 hidden md:flex items-center gap-2 bg-white dark:bg-[#18181B] border border-[#7C3AED]/30 text-zinc-900 dark:text-[#FAFAF9] px-3 py-1.5 rounded-full text-xs font-mono shadow-xl shadow-purple-500/10 z-10 animate-bounce" style={{ animationDuration: '4s' }}>
                        <span className="w-2 h-2 rounded-full bg-[#7C3AED]"></span>
                        OWASP mapping
                    </div>

                    <div className="rounded-2xl border border-zinc-200 dark:border-zinc-800 bg-zinc-50 dark:bg-[#18181B] shadow-2xl overflow-hidden relative flex flex-col hover:border-[#7C3AED]/50 transition-colors duration-300">
                        <div className="h-12 border-b border-zinc-100 dark:border-zinc-800 bg-zinc-50 dark:bg-[#09090B] flex items-center px-4 gap-2 flex-shrink-0">
                            <div className="w-3 h-3 rounded-full bg-red-400"></div>
                            <div className="w-3 h-3 rounded-full bg-amber-400"></div>
                            <div className="w-3 h-3 rounded-full bg-emerald-400"></div>
                            <div className="mx-auto text-xs text-zinc-400 font-mono bg-white dark:bg-zinc-900/50 px-3 py-1 rounded-md border border-zinc-200 dark:border-zinc-800 hidden sm:block">ai-kavach.vercel.app/scans/report</div>
                        </div>
                        <div className="flex-1 bg-zinc-100 dark:bg-zinc-900 p-2 sm:p-4">
                            <div className="relative rounded-lg overflow-hidden border border-purple-500/20 shadow-2xl shadow-purple-500/20 bg-white dark:bg-[#0a0a0a]">
                                <Image
                                    src="/screenshots/security-report-demo.png"
                                    alt="KAVACH Security Report - Real Scan Result"
                                    width={1920}
                                    height={1080}
                                    className="w-full h-auto object-cover"
                                    priority
                                />
                            </div>
                        </div>
                    </div>
                </Reveal>
            </div>
        </section>
    )
}
