'use client'

import * as Icons from './LandingIcons'
import Reveal from './Reveal'

export default function HeroSection() {
    return (
        <section className="relative overflow-hidden pt-24 pb-16 md:pt-32 md:pb-24 grid-pattern noise-overlay">
            <div className="absolute top-0 left-1/2 -translate-x-1/2 w-[1000px] h-[500px] opacity-30 dark:opacity-20 pointer-events-none">
                <div className="absolute inset-0 bg-gradient-to-r from-purple-400 to-indigo-400 blur-[100px] rounded-full mix-blend-multiply dark:mix-blend-screen" />
            </div>

            <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 relative z-10 text-center">
                <Reveal delay={0}>
                    <div className="inline-flex items-center rounded-full border border-purple-200 dark:border-purple-900/50 bg-purple-50 dark:bg-purple-900/10 px-4 py-1.5 text-sm font-mono text-purple-700 dark:text-purple-400 mb-8 shadow-sm">
                        <span className="mr-2 text-xs">▶</span> Currently in Beta · Free to Try
                    </div>
                </Reveal>

                <Reveal delay={100}>
                    <h1 className="text-5xl md:text-7xl font-heading font-bold tracking-tighter text-[#18181B] dark:text-[#FAFAF9] mb-4 leading-[1.1]">
                        AI writes your code. <br className="hidden md:block" />
                        <span className="font-accent italic text-[#7C3AED] font-normal tracking-normal">
                            We scan it for security holes.
                        </span>
                    </h1>
                </Reveal>

                <Reveal delay={200}>
                    <p className="mt-6 text-lg md:text-xl font-body text-zinc-600 dark:text-zinc-400 max-w-3xl mx-auto leading-relaxed">
                        The first security scanner built specifically for code generated by ChatGPT, Copilot, Cursor, and other AI tools. Catch logic flaws and OWASP Top 10 issues before you commit.
                    </p>
                </Reveal>

                <Reveal delay={300}>
                    <div className="mt-10 flex flex-col items-center justify-center space-y-4">
                        <button onClick={() => document.getElementById('beta-signup')?.scrollIntoView({ behavior: 'smooth' })} className="bg-gradient-to-b from-[#8B5CF6] to-[#7C3AED] text-white px-10 py-4 rounded-lg font-heading font-semibold text-lg transition-all shadow-[inset_0_1px_0_0_rgba(255,255,255,0.2)] hover:scale-[1.02] hover:shadow-xl hover:shadow-purple-500/25 flex items-center justify-center btn-ripple group">
                            <span className="flex items-center">Get Early Access <Icons.ArrowRight className="ml-2 h-5 w-5 group-hover:translate-x-1 transition-transform" /></span>
                        </button>
                        <a href="#demo" onClick={(e) => { e.preventDefault(); document.getElementById('demo')?.scrollIntoView({ behavior: 'smooth' }); }} className="text-sm font-body text-zinc-500 hover:text-[#7C3AED] transition-colors">
                            or watch the 30-second demo →
                        </a>
                    </div>
                </Reveal>

                <Reveal delay={400}>
                    <div className="mt-12 flex flex-col sm:flex-row items-center justify-center gap-4 sm:gap-8 text-sm text-zinc-500 dark:text-zinc-400 font-mono">
                        <div><span className="text-[#7C3AED] mr-2">•</span>Powered by Semgrep + Llama 3.1</div>
                        <div className="hidden sm:block opacity-30">|</div>
                        <div><span className="text-[#7C3AED] mr-2">•</span>Zero data retention</div>
                        <div className="hidden sm:block opacity-30">|</div>
                        <div><span className="text-[#7C3AED] mr-2">•</span>Open Source</div>
                    </div>
                </Reveal>

                <Reveal delay={600} className="mt-16 mx-auto max-w-5xl">
                    <div className="rounded-2xl border border-zinc-200 dark:border-zinc-800 bg-white dark:bg-[#18181B] shadow-2xl overflow-hidden aspect-video relative flex flex-col hover:border-[#7C3AED]/50 transition-colors duration-300">
                        <div className="h-12 border-b border-zinc-100 dark:border-zinc-800 bg-zinc-50 dark:bg-[#09090B] flex items-center px-4 gap-2">
                            <div className="w-3 h-3 rounded-full bg-red-400"></div>
                            <div className="w-3 h-3 rounded-full bg-amber-400"></div>
                            <div className="w-3 h-3 rounded-full bg-emerald-400"></div>
                            <div className="mx-auto text-xs text-zinc-400 font-mono">dashboard.kavach.dev</div>
                        </div>
                        <div className="flex-1 flex">
                            <div className="w-64 border-r border-zinc-100 dark:border-zinc-800 p-4 hidden md:block">
                                <div className="h-8 bg-zinc-100 dark:bg-zinc-800/50 rounded mb-4 w-3/4"></div>
                                <div className="space-y-3">
                                    {[...Array(5)].map((_, i) => (
                                        <div key={i} className="h-6 bg-zinc-50 dark:bg-[#09090B] rounded w-full"></div>
                                    ))}
                                </div>
                            </div>
                            <div className="flex-1 p-8">
                                <div className="flex justify-between items-end mb-8">
                                    <div>
                                        <div className="h-6 w-48 bg-zinc-200 dark:bg-zinc-800 rounded mb-2"></div>
                                        <div className="h-4 w-32 bg-zinc-100 dark:bg-zinc-900 rounded"></div>
                                    </div>
                                    <div className="w-24 h-24 rounded-full border-8 border-[#34D399] flex items-center justify-center">
                                        <span className="text-2xl font-heading font-bold text-[#34D399]">A</span>
                                    </div>
                                </div>
                                <div className="grid grid-cols-3 gap-4 mb-8">
                                    {[...Array(3)].map((_, i) => (
                                        <div key={i} className="h-24 bg-zinc-50 dark:bg-[#09090B] border border-zinc-100 dark:border-zinc-800 rounded-xl p-4">
                                            <div className="h-4 w-1/2 bg-zinc-200 dark:bg-zinc-800 rounded mb-4"></div>
                                            <div className="h-8 w-1/3 bg-zinc-300 dark:bg-zinc-700 rounded"></div>
                                        </div>
                                    ))}
                                </div>
                            </div>
                        </div>
                    </div>
                </Reveal>
            </div>
        </section>
    )
}
