// lib/markdown-report.ts
// KAVACH — Markdown Report Generator
// Generates downloadable security scan reports for all tiers

import type { Scan, Vulnerability, UserPlan, VulnerabilitySeverity } from '@/types'

// ─────────────────────────────────────────────────────────
// Types
// ─────────────────────────────────────────────────────────

export interface ReportOptions {
  scan: Scan & { projects?: { name?: string | null; repo_url?: string | null } | null }
  vulnerabilities: Vulnerability[]
  userPlan: UserPlan
  siteUrl?: string
  // V2.2 — Auto-fix confidence data (Pro+ only)
  autoFixData?: {
    fixed_files: Array<{
      file_path: string
      confidence?: {
        overall: number
        band: string
        label: string
        recommendation: string
      }
      vulnerabilities_fixed?: string[]
      lines_changed?: number
      status?: string
    }>
    fixed_count: number
    total_vulns: number
    completed_at: string | null
  } | null
}

// ─────────────────────────────────────────────────────────
// Emoji helpers
// ─────────────────────────────────────────────────────────

const SEVERITY_EMOJI: Record<VulnerabilitySeverity, string> = {
  CRITICAL: '🔴',
  HIGH:     '🟠',
  MEDIUM:   '🟡',
  LOW:      '🔵',
  INFO:     '⚪',
}

const GRADE_EMOJI: Record<string, string> = {
  'A+': '🏆',
  'A':  '✅',
  'B':  '👍',
  'C':  '⚠️',
  'D':  '🚨',
  'F':  '💀',
}

function gradeLabel(grade: string | null): string {
  const labels: Record<string, string> = {
    'A+': 'Excellent',
    'A':  'Very Good',
    'B':  'Good',
    'C':  'Fair — Needs Attention',
    'D':  'Poor — Serious Risks',
    'F':  'Dangerous — Immediate Action Required',
  }
  return labels[grade ?? ''] ?? 'Unknown'
}

// ─────────────────────────────────────────────────────────
// Main generator
// ─────────────────────────────────────────────────────────

export function generateMarkdownReport(opts: ReportOptions): string {
  const { scan, vulnerabilities, userPlan, siteUrl = 'https://ai-kavach.vercel.app', autoFixData } = opts

  const isPro = userPlan === 'pro' || userPlan === 'enterprise'
  const isEnterprise = userPlan === 'enterprise'

  const projectName = scan.projects?.name ?? 'Untitled Project'
  const repoUrl = scan.projects?.repo_url ?? null
  const scanDate = new Date(scan.created_at).toLocaleString('en-US', {
    year: 'numeric', month: 'long', day: 'numeric',
    hour: '2-digit', minute: '2-digit', timeZoneName: 'short',
  })
  const shortId = scan.id.slice(0, 8)

  // Group vulns by severity
  const bySeverity: Record<VulnerabilitySeverity, Vulnerability[]> = {
    CRITICAL: [], HIGH: [], MEDIUM: [], LOW: [], INFO: [],
  }
  vulnerabilities.forEach(v => {
    const sev = (v.severity ?? 'INFO') as VulnerabilitySeverity
    bySeverity[sev].push(v)
  })

  // ─── Build report ─────────────────────────────────────

  const parts: string[] = []

  // Header
  parts.push(`# 🛡️ KAVACH Security Scan Report`)
  parts.push('')
  parts.push(`> Generated by [KAVACH AI Security Scanner](${siteUrl}) — Report your security posture in seconds.`)
  parts.push('')
  parts.push(`---`)
  parts.push('')

  // Overview
  parts.push(`## 📋 Overview`)
  parts.push('')
  parts.push(`| Field | Value |`)
  parts.push(`|-------|-------|`)
  parts.push(`| **Project** | ${projectName} |`)
  if (repoUrl) parts.push(`| **Repository** | ${repoUrl} |`)
  parts.push(`| **Scan ID** | \`${shortId}\` |`)
  parts.push(`| **Date** | ${scanDate} |`)
  parts.push(`| **Files Scanned** | ${scan.files_scanned ?? 0} |`)
  parts.push(`| **Lines Scanned** | ${(scan.lines_scanned ?? 0).toLocaleString()} |`)
  parts.push(`| **Analysis Engine** | ${scan.analysis_engine ?? 'Semgrep + AI + Gitleaks'} |`)
  if (isPro) {
    parts.push(`| **AI Model** | ${scan.llm_model ?? 'Qwen 2.5 Coder'} |`)
    parts.push(`| **Scan Duration** | ${scan.scan_duration_seconds ?? 0}s |`)
  }
  parts.push('')

  // Security Score
  const score = scan.security_score ?? 0
  const grade = scan.grade ?? 'F'
  const gradeIcon = GRADE_EMOJI[grade] ?? '❓'

  parts.push(`## ${gradeIcon} Security Score: ${score}/100 (Grade ${grade})`)
  parts.push('')
  parts.push(`**Verdict:** ${gradeLabel(grade)}`)
  parts.push('')

  // Score meter (ASCII)
  const filled = Math.round(score / 5)  // 20 blocks max
  const meter = '█'.repeat(filled) + '░'.repeat(20 - filled)
  parts.push(`\`\`\``)
  parts.push(`${meter}  ${score}/100`)
  parts.push(`\`\`\``)
  parts.push('')

  // Executive Summary
  parts.push(`## 📊 Executive Summary`)
  parts.push('')
  parts.push(`Found **${scan.total_vulnerabilities ?? 0} vulnerabilities** across ${scan.files_scanned ?? 0} files.`)
  parts.push('')
  parts.push(`| Severity | Count | % of Total |`)
  parts.push(`|----------|-------|------------|`)

  const total = scan.total_vulnerabilities ?? 0
  const pct = (n: number) => total > 0 ? `${Math.round((n / total) * 100)}%` : '0%'

  parts.push(`| ${SEVERITY_EMOJI.CRITICAL} Critical | ${scan.critical_count ?? 0} | ${pct(scan.critical_count ?? 0)} |`)
  parts.push(`| ${SEVERITY_EMOJI.HIGH} High | ${scan.high_count ?? 0} | ${pct(scan.high_count ?? 0)} |`)
  parts.push(`| ${SEVERITY_EMOJI.MEDIUM} Medium | ${scan.medium_count ?? 0} | ${pct(scan.medium_count ?? 0)} |`)
  parts.push(`| ${SEVERITY_EMOJI.LOW} Low | ${scan.low_count ?? 0} | ${pct(scan.low_count ?? 0)} |`)
  parts.push(`| ${SEVERITY_EMOJI.INFO} Info | ${scan.info_count ?? 0} | ${pct(scan.info_count ?? 0)} |`)
  parts.push('')

  // V2.2 — Auto-Fix Results section (Pro+ only, only if auto-fix ran)
  if (isPro && autoFixData && autoFixData.fixed_files.length > 0) {
    const successfulFixes = autoFixData.fixed_files.filter(f => f.status === 'fixed' && f.confidence)

    if (successfulFixes.length > 0) {
      // Calculate average confidence
      const avgConfidence = Math.round(
        successfulFixes.reduce((sum, f) => sum + (f.confidence?.overall ?? 0), 0) / successfulFixes.length
      )

      const avgBandEmoji =
        avgConfidence >= 90 ? '🟢' :
        avgConfidence >= 70 ? '🟡' :
        avgConfidence >= 50 ? '🟠' : '🔴'

      parts.push(`## 🎯 Auto-Fix Results (KAVACH AI)`)
      parts.push('')
      parts.push(`**${autoFixData.fixed_count} of ${autoFixData.total_vulns} vulnerabilities auto-fixed by KAVACH's AI**`)
      parts.push('')
      parts.push(`**Average Fix Confidence:** ${avgBandEmoji} **${avgConfidence}%**`)
      parts.push('')
      parts.push(`### Per-File Confidence Breakdown`)
      parts.push('')
      parts.push(`| File | Vulnerabilities Fixed | Lines Changed | Confidence |`)
      parts.push(`|------|----------------------|---------------|------------|`)

      successfulFixes.forEach(f => {
        const conf = f.confidence!
        const bandEmoji =
          conf.overall >= 90 ? '🟢' :
          conf.overall >= 70 ? '🟡' :
          conf.overall >= 50 ? '🟠' : '🔴'
        const cleanPath = cleanFilePath(f.file_path)
        parts.push(
          `| \`${cleanPath}\` | ${f.vulnerabilities_fixed?.length ?? 0} | ${f.lines_changed ?? 0} | ${bandEmoji} ${conf.overall}% (${conf.label}) |`
        )
      })
      parts.push('')

      // Recommendation callout
      const lowConfidenceFiles = successfulFixes.filter(f => (f.confidence?.overall ?? 100) < 70)
      if (lowConfidenceFiles.length > 0) {
        parts.push(`> ⚠️ **Review Recommended:** ${lowConfidenceFiles.length} file${lowConfidenceFiles.length === 1 ? '' : 's'} scored below 70% confidence. Please review the fixes carefully before merging to production.`)
        parts.push('')
      } else {
        parts.push(`> ✅ **High Confidence:** All fixes scored 70% or higher. Still recommended to review changes before merging.`)
        parts.push('')
      }

      parts.push(`---`)
      parts.push('')
    }
  }

  // Priority Recommendations
  if ((scan.critical_count ?? 0) > 0 || (scan.high_count ?? 0) > 0) {
    parts.push(`## 🚨 Priority Recommendations`)
    parts.push('')
    if ((scan.critical_count ?? 0) > 0) {
      parts.push(`1. **Fix ${scan.critical_count} Critical vulnerabilities immediately** — these are exploitable and pose immediate risk.`)
    }
    if ((scan.high_count ?? 0) > 0) {
      parts.push(`2. **Address ${scan.high_count} High severity issues within 7 days** — significant security risk.`)
    }
    if ((scan.medium_count ?? 0) > 0) {
      parts.push(`3. **Plan fixes for ${scan.medium_count} Medium severity issues within the current sprint.**`)
    }
    parts.push('')

    if (!isPro) {
      parts.push(`> 💡 **Upgrade to Pro** to get one-click Auto-Fix for all vulnerabilities.`)
      parts.push(`> Try KAVACH Pro: ${siteUrl}`)
      parts.push('')
    }
  }

  parts.push(`---`)
  parts.push('')

  // Detailed Vulnerabilities
  parts.push(`## 🔍 Detailed Findings`)
  parts.push('')

  const severityOrder: VulnerabilitySeverity[] = ['CRITICAL', 'HIGH', 'MEDIUM', 'LOW', 'INFO']

  for (const sev of severityOrder) {
    const vulns = bySeverity[sev]
    if (vulns.length === 0) continue

    parts.push(`### ${SEVERITY_EMOJI[sev]} ${capitalize(sev.toLowerCase())} Severity (${vulns.length})`)
    parts.push('')

    vulns.forEach((v, idx) => {
      parts.push(`#### ${idx + 1}. ${v.name}`)
      parts.push('')

      // Metadata table
      const metaRows: string[] = []
      if (v.file_path) metaRows.push(`| **File** | \`${cleanFilePath(v.file_path)}\` |`)
      if (v.line_number) metaRows.push(`| **Line** | ${v.line_number}${v.line_end ? `-${v.line_end}` : ''} |`)
      if (v.owasp_id) metaRows.push(`| **OWASP** | ${v.owasp_id}${v.owasp_category ? ` — ${v.owasp_category}` : ''} |`)
      if (v.cwe_id) metaRows.push(`| **CWE** | ${v.cwe_id} |`)
      if (v.detection_method) metaRows.push(`| **Detected by** | ${v.tool_name ?? v.detection_method} |`)

      if (metaRows.length > 0) {
        parts.push(`| | |`)
        parts.push(`|---|---|`)
        parts.push(...metaRows)
        parts.push('')
      }

      // Description
      if (v.description) {
        parts.push(`**Description:**  `)
        parts.push(v.description)
        parts.push('')
      }

      // PRO+ tier: Full code snippets and AI explanations
      if (isPro) {
        const cleanPath = cleanFilePath(v.file_path)
        if (v.vulnerable_code) {
          parts.push(`**Vulnerable Code:**`)
          parts.push('```' + detectLangFromPath(cleanPath))
          parts.push(v.vulnerable_code)
          parts.push('```')
          parts.push('')
        }

        if (v.fixed_code) {
          parts.push(`**Recommended Fix:**`)
          parts.push('```' + detectLangFromPath(cleanPath))
          parts.push(v.fixed_code)
          parts.push('```')
          parts.push('')
        }

        if (v.ai_explanation) {
          parts.push(`**Why This Is Dangerous:**  `)
          parts.push(v.ai_explanation)
          parts.push('')
        }

        if (v.ai_fix_explanation) {
          parts.push(`**How The Fix Works:**  `)
          parts.push(v.ai_fix_explanation)
          parts.push('')
        }

        if (v.why_ai_makes_this_mistake) {
          parts.push(`**Why AI Coding Tools Make This Mistake:**  `)
          parts.push(v.why_ai_makes_this_mistake)
          parts.push('')
        }
      } else {
        // FREE tier: Just show hint
        parts.push(`> 💎 **Upgrade to Pro** to see the vulnerable code snippet, recommended fix, and AI-powered explanation.`)
        parts.push('')
      }

      parts.push(`---`)
      parts.push('')
    })
  }

  // Empty state
  if (vulnerabilities.length === 0) {
    parts.push(`### ✅ No Vulnerabilities Found`)
    parts.push('')
    parts.push(`Great work! Your code passed all security checks.`)
    parts.push('')
    parts.push(`Keep scanning regularly to catch new issues as your code evolves.`)
    parts.push('')
  }

  // Footer
  parts.push(`## 🛡️ About KAVACH`)
  parts.push('')
  parts.push(`KAVACH is an open-source AI security scanner that detects vulnerabilities in AI-generated code (ChatGPT, Copilot, Cursor, Bolt.new, v0.dev).`)
  parts.push('')
  parts.push(`**Multi-layer analysis:**`)
  parts.push(`- 🔍 **Semgrep** — static code analysis for known patterns`)
  parts.push(`- 🤖 **Qwen 2.5 Coder AI** — context-aware vulnerability detection`)
  parts.push(`- 🔑 **Gitleaks** — hardcoded secret detection`)
  parts.push('')
  parts.push(`**Coverage:** OWASP Top 10 + CWE Top 25`)
  parts.push('')

  if (!isPro) {
    parts.push(`### 💎 Unlock More With Pro`)
    parts.push('')
    parts.push(`- ⚡ One-click Auto-Fix for all vulnerabilities`)
    parts.push(`- 📥 Download fixed files as ZIP`)
    parts.push(`- 📊 Detailed reports with code snippets`)
    parts.push(`- 🔍 Scan history and comparison`)
    parts.push(`- 100 scans/month`)
    parts.push('')
  }

  if (!isEnterprise) {
    parts.push(`### 🏢 Enterprise Features`)
    parts.push('')
    parts.push(`- 🔀 One-click GitHub PR creation`)
    parts.push(`- ♾️ Unlimited scans`)
    parts.push(`- 🔒 SARIF export for compliance`)
    parts.push(`- 👥 Team collaboration`)
    parts.push(`- 🚦 CI/CD integration`)
    parts.push('')
  }

  parts.push(`---`)
  parts.push('')
  parts.push(`**🌐 Website:** ${siteUrl}`)
  parts.push(`**💻 GitHub:** https://github.com/Tauqeer7Khan/Kavach`)
  parts.push(`**📧 Built by:** [Tauqeer Khan](https://www.linkedin.com/in/tauqeer7khan)`)
  parts.push('')
  parts.push(`*Report generated on ${new Date().toISOString()}*`)
  parts.push('')

  return parts.join('\n')
}

// ─────────────────────────────────────────────────────────
// Helpers
// ─────────────────────────────────────────────────────────

function capitalize(str: string): string {
  return str.charAt(0).toUpperCase() + str.slice(1)
}

// Strip /tmp/kavach-scans/{scanId}/ prefix from file paths
// (Sometimes present when Gitleaks reports files with absolute paths)
function cleanFilePath(filePath: string | null): string {
  if (!filePath) return ''
  let clean = filePath
  if (clean.startsWith('/tmp/kavach-scans/')) {
    const parts = clean.split('/')
    if (parts.length > 4) {
      clean = parts.slice(4).join('/')
    }
  }
  clean = clean.replace(/^\/+/, '')
  return clean
}

function detectLangFromPath(filePath: string | null): string {
  if (!filePath) return ''
  const ext = filePath.split('.').pop()?.toLowerCase() ?? ''
  const map: Record<string, string> = {
    js: 'javascript', jsx: 'javascript', mjs: 'javascript', cjs: 'javascript',
    ts: 'typescript', tsx: 'typescript',
    py: 'python', pyw: 'python',
    java: 'java',
    go: 'go',
    rb: 'ruby',
    php: 'php',
    rs: 'rust',
    c: 'c', h: 'c',
    cpp: 'cpp', cc: 'cpp', hpp: 'cpp',
    cs: 'csharp',
    sh: 'bash',
    yaml: 'yaml', yml: 'yaml',
    json: 'json',
    env: 'bash',
    md: 'markdown',
  }
  return map[ext] ?? ''
}
