// app/api/scans/[id]/auto-fix/download/route.ts
// KAVACH V2 — Download Auto-Fixed Files as ZIP
// Pro/Enterprise only. Auto-finds latest fix job or accepts fixJobId param.

import { NextRequest, NextResponse } from 'next/server'
import { createClient } from '@/lib/supabase-server'
import JSZip from 'jszip'

// ── Types ──────────────────────────────────────────────
interface FixedFile {
  file_path: string
  original_content: string
  fixed_content: string
  status: 'fixed' | 'skipped' | 'failed'
  lines_changed: number
  vulnerabilities_fixed: string[]
  skip_reason?: string
}

// ── Helpers ────────────────────────────────────────────

/**
 * Extract clean filename from potentially messy paths.
 * "/tmp/kavach-scans/uuid/code.js" → "code.js"
 * "src/app.ts" → "src/app.ts" (preserved)
 */
function cleanFilePath(rawPath: string): string {
  // Strip /tmp/kavach-scans/[uuid]/ prefix if present
  const tmpMatch = rawPath.match(/\/tmp\/kavach-scans\/[^/]+\/(.+)$/)
  if (tmpMatch) return tmpMatch[1]

  // Strip any leading slash
  return rawPath.replace(/^\/+/, '')
}

/**
 * Build human-readable Markdown report of what was fixed.
 */
function buildReport(
  scanId: string,
  fixedFiles: FixedFile[],
  jobDate: string,
  totalVulns: number
): string {
  const fixed   = fixedFiles.filter(f => f.status === 'fixed')
  const skipped = fixedFiles.filter(f => f.status === 'skipped')
  const failed  = fixedFiles.filter(f => f.status === 'failed')

  const vulnsFixed = fixed.reduce(
    (sum, f) => sum + (f.vulnerabilities_fixed?.length ?? 0),
    0
  )

  let md = `# 🛡️ KAVACH Auto-Fix Report

**Scan ID:** \`${scanId}\`
**Generated:** ${new Date(jobDate).toLocaleString()}
**Files Processed:** ${fixedFiles.length}

## Summary

| Status | Count |
|--------|-------|
| ✅ Fixed   | ${fixed.length} files |
| ⏭️ Skipped | ${skipped.length} files |
| ❌ Failed  | ${failed.length} files |
| 🔧 Vulnerabilities Patched | ${vulnsFixed} of ${totalVulns} |

`

  if (fixed.length > 0) {
    md += `## ✅ Successfully Fixed Files\n\n`
    for (const f of fixed) {
      md += `### \`${cleanFilePath(f.file_path)}\`\n\n`
      md += `- **Lines changed:** ${f.lines_changed}\n`
      md += `- **Vulnerabilities patched:** ${f.vulnerabilities_fixed?.length ?? 0}\n\n`
    }
  }

  if (skipped.length > 0) {
    md += `## ⏭️ Skipped Files\n\n`
    for (const f of skipped) {
      md += `### \`${cleanFilePath(f.file_path)}\`\n\n`
      md += `- **Reason:** ${f.skip_reason ?? 'Unknown'}\n\n`
    }
  }

  if (failed.length > 0) {
    md += `## ❌ Failed Files\n\n`
    for (const f of failed) {
      md += `### \`${cleanFilePath(f.file_path)}\`\n\n`
      md += `- **Reason:** ${f.skip_reason ?? 'AI could not generate a valid fix'}\n\n`
    }
  }

  md += `---

## How to Apply These Fixes

1. Review each file in the \`fixed/\` folder against your project
2. Compare with the \`original/\` folder to see exactly what changed
3. Look for \`// KAVACH-FIX:\` comments — these mark security patches
4. Copy the fixed files into your project
5. Run your test suite to verify nothing broke
6. Commit with a message like: \`security: apply KAVACH auto-fixes\`

## ⚠️ Important Notes

- All fixes are **surgical** — only vulnerable lines changed
- Some fixes may require adding missing imports (e.g. \`require('child_process')\`)
- Review the diff carefully before merging to production
- No unrelated code was refactored, renamed, or modernized

## Need Help?

- Docs: https://ai-kavach.vercel.app/docs
- Issues: https://github.com/Tauqeer7Khan/Kavach/issues

*Generated by KAVACH — Because AI-generated code needs a security guard.*
`

  return md
}

/**
 * Simple README for the ZIP.
 */
function buildReadme(): string {
  return `KAVACH Auto-Fix Package
========================

This ZIP contains security-patched versions of your files.

FOLDERS:
--------
  fixed/     Your files with security fixes applied
  original/  Your original files (unchanged, for comparison)

FILES:
------
  KAVACH-REPORT.md  Human-readable summary of what was fixed
  README.txt        This file

HOW TO USE:
-----------
1. Open KAVACH-REPORT.md to see what was changed
2. Compare 'fixed/' vs 'original/' to review diffs
3. Look for '// KAVACH-FIX:' comments — these mark security patches
4. Copy 'fixed/' files into your project
5. Run your tests to verify
6. Commit the changes

IMPORTANT:
----------
KAVACH performs SURGICAL fixes — only the vulnerable lines are changed.
The AI does NOT refactor, optimize, or modify unrelated code.

Some fixes may require you to add missing imports (e.g. 'require child_process').
Review the diff carefully before merging.

Learn more: https://ai-kavach.vercel.app
`
}

// ── Route Handler ──────────────────────────────────────

export async function GET(
  req: NextRequest,
  { params }: { params: { id: string } }
) {
  try {
    const supabase = await createClient()
    const { data: { user } } = await supabase.auth.getUser()

    if (!user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
    }

    // ── Tier check — Pro or Enterprise only ─────────────
    const { data: userData } = await supabase
      .from('users')
      .select('plan')
      .eq('id', user.id)
      .single()

    const plan = userData?.plan ?? 'free'
    if (plan === 'free') {
      return NextResponse.json(
        {
          error: 'Pro tier required',
          upgradeRequired: true,
          message: 'Download fixed files is available on Pro and Enterprise plans.',
        },
        { status: 403 }
      )
    }

    const scanId = params.id

    // ── Verify scan belongs to user ─────────────────────
    const { data: scan, error: scanError } = await supabase
      .from('scans')
      .select('id, user_id')
      .eq('id', scanId)
      .eq('user_id', user.id)
      .single()

    if (scanError || !scan) {
      return NextResponse.json(
        { error: 'Scan not found or access denied' },
        { status: 404 }
      )
    }

    // ── Get fix job — either by explicit ID or latest completed ─
    const requestedFixJobId = req.nextUrl.searchParams.get('fixJobId')

    let fixJobQuery = supabase
      .from('auto_fix_jobs')
      .select('*')
      .eq('scan_id', scanId)
      .eq('user_id', user.id)
      .eq('status', 'completed')

    if (requestedFixJobId) {
      fixJobQuery = fixJobQuery.eq('id', requestedFixJobId)
    } else {
      fixJobQuery = fixJobQuery.order('created_at', { ascending: false }).limit(1)
    }

    const { data: fixJob, error: jobError } = await fixJobQuery.single()

    if (jobError || !fixJob) {
      return NextResponse.json(
        {
          error: 'No completed fix job found',
          message: requestedFixJobId
            ? 'Fix job not found or not completed.'
            : 'Run Auto-Fix first before downloading.',
        },
        { status: 404 }
      )
    }

    const fixedFiles = (fixJob.fixed_files ?? []) as FixedFile[]

    if (fixedFiles.length === 0) {
      return NextResponse.json(
        { error: 'Fix job has no files to download' },
        { status: 404 }
      )
    }

    // ── Build the ZIP ───────────────────────────────────
    const zip = new JSZip()

    // Root files
    zip.file('README.txt', buildReadme())
    zip.file('KAVACH-REPORT.md', buildReport(
      scanId,
      fixedFiles,
      fixJob.created_at,
      fixJob.total_vulns ?? 0
    ))

    // Add each file (fixed + original for comparison)
    const fixedFolder    = zip.folder('fixed')
    const originalFolder = zip.folder('original')

    if (!fixedFolder || !originalFolder) {
      throw new Error('Failed to create ZIP folders')
    }

    let addedFiles = 0
    for (const f of fixedFiles) {
      const cleanPath = cleanFilePath(f.file_path)
      if (!cleanPath) continue

      // Only include actually-fixed files in fixed/
      if (f.status === 'fixed' && f.fixed_content) {
        fixedFolder.file(cleanPath, f.fixed_content)
        addedFiles++
      }

      // Always include original if available (for diff review)
      if (f.original_content) {
        originalFolder.file(cleanPath, f.original_content)
      }
    }

    if (addedFiles === 0) {
      return NextResponse.json(
        {
          error: 'No files were successfully fixed',
          message: 'The auto-fix job completed but produced no usable output.',
        },
        { status: 404 }
      )
    }

    // ── Generate the ZIP buffer ─────────────────────────
    const zipBuffer = await zip.generateAsync({
      type: 'nodebuffer',
      compression: 'DEFLATE',
      compressionOptions: { level: 6 },
    })

    // ── Return as download ──────────────────────────────
    const shortId = scanId.slice(0, 8)
    
    // Use IST (India Standard Time) for filename date.
    // Server may run in UTC (Vercel default) but users are in India.
    // Intl.DateTimeFormat gives explicit timezone control.
    const dateStr = new Intl.DateTimeFormat('en-CA', {
      timeZone: 'Asia/Kolkata',
      year:  'numeric',
      month: '2-digit',
      day:   '2-digit',
    }).format(new Date())
    // 'en-CA' produces YYYY-MM-DD format naturally
    
    const filename = `kavach-fixes-${shortId}-${dateStr}.zip`

    return new NextResponse(new Uint8Array(zipBuffer), {
      status: 200,
      headers: {
        'Content-Type':        'application/zip',
        'Content-Disposition': `attachment; filename="${filename}"`,
        'Content-Length':      zipBuffer.length.toString(),
        'Cache-Control':       'no-store',
      },
    })

  } catch (err) {
    console.error('Download fixes error:', err)
    const errorMessage = err instanceof Error ? err.message : 'Failed to generate ZIP'
    return NextResponse.json(
      { error: errorMessage },
      { status: 500 }
    )
  }
}
