// app/api/scans/[id]/auto-fix/download/route.ts

import { NextRequest, NextResponse } from 'next/server'
import { createClient } from '@/lib/supabase-server'
import JSZip from 'jszip'

export async function GET(
  req: NextRequest,
  { params }: { params: { id: string } }
) {
  try {
    const supabase = await createClient()
    const { data: { user } } = await supabase.auth.getUser()

    if (!user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
    }

    const fixJobId = req.nextUrl.searchParams.get('fixJobId')
    if (!fixJobId) {
      return NextResponse.json(
        { error: 'fixJobId query parameter required' },
        { status: 400 }
      )
    }

    // Fetch the fix job
    const { data: fixJob, error } = await supabase
      .from('auto_fix_jobs')
      .select('*')
      .eq('id', fixJobId)
      .eq('user_id', user.id)
      .single()

    if (error || !fixJob) {
      return NextResponse.json(
        { error: 'Fix job not found or access denied' },
        { status: 404 }
      )
    }

    if (fixJob.status !== 'completed') {
      return NextResponse.json(
        { error: 'Fix job is not completed yet' },
        { status: 422 }
      )
    }

    const fixedFiles = fixJob.fixed_files as Array<{
      file_path: string
      fixed_content: string
      original_content: string
      status: string
      vulnerabilities_fixed: string[]
      lines_changed: number
      skip_reason?: string
    }>

    // Build ZIP
    const zip = new JSZip()

    // Add fixed files
    const successfulFixes = fixedFiles.filter(f => f.status === 'fixed')

    for (const file of successfulFixes) {
      // Preserve folder structure inside ZIP
      const zipPath = file.file_path.startsWith('/')
        ? file.file_path.slice(1)
        : file.file_path
      zip.file(zipPath, file.fixed_content)
    }

    // Add a KAVACH_FIX_SUMMARY.md
    const summary = buildSummaryMarkdown(fixJob, fixedFiles)
    zip.file('KAVACH_FIX_SUMMARY.md', summary)

    // Generate ZIP buffer
    const zipBuffer = await zip.generateAsync({
      type:               'nodebuffer',
      compression:        'DEFLATE',
      compressionOptions: { level: 6 },
    })

    const scanId  = params.id
    const dateStr = new Date().toISOString().split('T')[0]
    const filename = `kavach-fixes-${scanId.slice(0, 8)}-${dateStr}.zip`

    return new NextResponse(zipBuffer as any, {
      status:  200,
      headers: {
        'Content-Type':        'application/zip',
        'Content-Disposition': `attachment; filename="${filename}"`,
        'Content-Length':      zipBuffer.length.toString(),
      },
    })

  } catch (err: any) {
    console.error('Download ZIP error:', err)
    return NextResponse.json(
      { error: err.message || 'Failed to generate ZIP' },
      { status: 500 }
    )
  }
}

function buildSummaryMarkdown(
  fixJob: any,
  fixedFiles: any[]
): string {
  const date    = new Date().toLocaleDateString('en-US', {
    year: 'numeric', month: 'long', day: 'numeric'
  })
  const fixed   = fixedFiles.filter(f => f.status === 'fixed')
  const skipped = fixedFiles.filter(f => f.status === 'skipped')
  const failed  = fixedFiles.filter(f => f.status === 'failed')

  const fileList = fixed.map(f =>
    `- \`${f.file_path}\` — ${f.vulnerabilities_fixed.length} vulnerabilities fixed, ${f.lines_changed} lines changed`
  ).join('\n')

  const skippedList = [...skipped, ...failed].map(f =>
    `- \`${f.file_path}\` — ${f.skip_reason ?? 'unknown reason'}`
  ).join('\n')

  return `# 🛡️ KAVACH Auto-Fix Summary

**Date:** ${date}
**Scan ID:** ${fixJob.scan_id}
**Total Vulnerabilities:** ${fixJob.total_vulns}

## ✅ Fixed Files (${fixed.length})

${fileList || 'None'}

## ⏭️ Skipped / Failed Files (${skipped.length + failed.length})

${skippedList || 'None'}

## ⚠️ Important Notes

- Review every change before deploying to production
- Run your full test suite after applying these fixes
- These fixes address security vulnerabilities only
- No other code was modified

## 🔒 What Was Fixed

All fixes were applied with surgical precision.
Only the vulnerable lines were changed.
Each fix is marked with a // KAVACH-FIX: comment.

---
*Generated by KAVACH AI Security Scanner*
*https://ai-kavach.vercel.app*
`
}
